[project]
name = "sito-punti"
version = "0.0.20"
requires-python = ">=3.11"
dependencies = [
  "Flask==3.1.2",
  "Flask-Login==0.6.3",
  "Flask-SQLAlchemy>=3.1.0,<4.0.0",
  "Flask-CORS>=5.0.0",
  "SQLAlchemy==2.0.43",
  "pandas==2.3.2",
  "openpyxl==3.1.5",
  "Werkzeug>=3.1.0,<4.0.0",
  "python-dotenv>=1.2.1",
  "pydantic[email]>=2.0.0",
  "pytest>=8.0.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["api*"]

[tool.pyright]
venvPath = "."
venv = ".venv"
reportMissingTypeStubs = false
reportAttributeAccessIssue = false
reportCallIssue = false
reportArgumentType = false
reportOptionalMemberAccess = false

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4"] # rule set for code convenction,https://docs.astral.sh/ruff/rules/ 
ignore = ["E501"] # line-too long

[tool.ruff.format]
quote-style = "double"
